# -*- coding: utf-8 -*-
"""code.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUw1asLaTIZtWELmrGg80yHf8KebTHmu

# Multimodal Fusion (CNN + Text) - Freeze/Unfreeze Case Study
"""

import torch
import torch.nn as nn
import random
import copy
import itertools
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, transforms

SEED = 42
random.seed(SEED)
torch.manual_seed(SEED)  # FIX: co dinh seed de 4 case xuat phat cung dieu kien khi can so sanh doc lap

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d puneet6060/intel-image-classification
!unzip -q intel-image-classification.zip

transform = transforms.Compose([
    transforms.Resize((150, 150)),
    transforms.ToTensor(),
])

train_dataset = datasets.ImageFolder("seg_train/seg_train", transform=transform)
test_dataset  = datasets.ImageFolder("seg_test/seg_test",  transform=transform)

captions = {
    0: [
        "modern buildings in the city",
        "urban skyline with tall skyscrapers",
        "city street lined with buildings"
    ],
    1: [
        "dense green forest",
        "thick forest full of trees",
        "green woodland scenery"
    ],
    2: [
        "beautiful glacier covered with ice",
        "icy glacier landscape with snow",
        "frozen glacier under the sky"
    ],
    3: [
        "high mountain landscape",
        "tall mountain peak scenery",
        "mountain range under the sky"
    ],
    4: [
        "blue sea with water",
        "ocean waves near the shore",
        "sea view with blue water"
    ],
    5: [
        "urban street with roads",
        "city road full of traffic",
        "street with parked cars"
    ]
}

words = set()

for variants in captions.values():
    for s in variants:
        words.update(s.split())

word2idx = {w: i + 1 for i, w in enumerate(sorted(words))}
word2idx["<pad>"] = 0

max_len = max(len(s.split()) for variants in captions.values() for s in variants)  # FIX: pad theo max_len that, khong hardcode

class MultiModalDataset(Dataset):

    def __init__(self, base_dataset, train_mode=True):
        self.base = base_dataset
        self.train_mode = train_mode  # True: random chon 1 trong cac caption variant (augment). False: luon lay variant dau (eval on dinh)

    def __len__(self):
        return len(self.base)

    def __getitem__(self, idx):
        image, label = self.base[idx]

        variants = captions[label]
        sentence = random.choice(variants) if self.train_mode else variants[0]

        tokens = [word2idx[w] for w in sentence.split()]
        tokens = tokens[:max_len] + [0] * (max_len - len(tokens))  # FIX: pad/truncate co dinh, tranh crash o collate
        tokens = torch.tensor(tokens)

        return image, tokens, label

trainloader = DataLoader(
    MultiModalDataset(train_dataset, train_mode=True),
    batch_size=64,
    shuffle=True
)

testloader = DataLoader(
    MultiModalDataset(test_dataset, train_mode=False),  # FIX: truoc day test_loader tao san khong wrap qua MultiModalDataset, khong dung duoc
    batch_size=64,
    shuffle=False
)

class ImageEncoder(nn.Module):

    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),

            nn.AdaptiveAvgPool2d(1)
        )

        self.norm = nn.LayerNorm(32)  # FIX: chuan hoa scale truoc khi concat voi text feature

    def forward(self, x):
        x = self.net(x)
        x = x.flatten(1)
        return self.norm(x)

class TextEncoder(nn.Module):

    def __init__(self):
        super().__init__()

        self.embedding = nn.Embedding(len(word2idx), 16, padding_idx=0)  # FIX: padding_idx=0, tranh pad token lam lech mean pooling
        self.norm = nn.LayerNorm(16)  # FIX: chuan hoa scale truoc khi concat voi image feature

    def forward(self, x):
        emb = self.embedding(x)
        pooled = emb.mean(dim=1)
        return self.norm(pooled)

class FusionModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.image = ImageEncoder()
        self.text = TextEncoder()

        self.fc = nn.Sequential(
            nn.Linear(48, 32),
            nn.ReLU(),
            nn.Linear(32, len(captions))  # FIX: 10 -> so class thuc te
        )

    def forward(self, image, text):
        img = self.image(image)
        txt = self.text(text)
        feature = torch.cat([img, txt], dim=1)
        return self.fc(feature)

def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0

    with torch.no_grad():
        for images, texts, labels in loader:
            images, texts, labels = images.to(device), texts.to(device), labels.to(device)

            outputs = model(images, texts)
            loss = criterion(outputs, labels)

            total_loss += loss.item()
            correct += (outputs.argmax(1) == labels).sum().item()
            total += labels.size(0)

    return total_loss / len(loader), correct / total

def train_one_case(name, model, optimizer, criterion, device, epochs):
    model.to(device)
    history = {"train_loss": [], "train_acc": [], "test_loss": [], "test_acc": []}

    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0

        for images, texts, labels in trainloader:
            images, texts, labels = images.to(device), texts.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images, texts)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            correct += (outputs.argmax(1) == labels).sum().item()
            total += labels.size(0)

        train_loss = running_loss / len(trainloader)
        train_acc = correct / total
        test_loss, test_acc = evaluate(model, testloader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["test_loss"].append(test_loss)
        history["test_acc"].append(test_acc)

        print(f"[{name}] Epoch {epoch+1}/{epochs} | "
              f"train_loss={train_loss:.4f} train_acc={train_acc:.4f} | "
              f"test_loss={test_loss:.4f} test_acc={test_acc:.4f}")

    return history

device = "cuda" if torch.cuda.is_available() else "cpu"
EPOCHS = 8
device

"""# Trường hợp 1: Freeze CNN + Text, chỉ Fusion (fc) học"""

model1 = FusionModel()

for p in model1.image.parameters():
    p.requires_grad = False

for p in model1.text.parameters():
    p.requires_grad = False

criterion = nn.CrossEntropyLoss()

optimizer1 = torch.optim.Adam(model1.fc.parameters(), lr=1e-3)

history1 = train_one_case("Case1", model1, optimizer1, criterion, device, EPOCHS)

"""# Trường hợp 2: Freeze Text, train CNN + Fusion"""

model2 = FusionModel()

for p in model2.image.parameters():
    p.requires_grad = True   # CNN train

for p in model2.text.parameters():
    p.requires_grad = False  # text freeze

optimizer2 = torch.optim.Adam([
    {"params": model2.image.parameters(), "lr": 1e-4},
    {"params": model2.fc.parameters(),    "lr": 1e-3},
])

history2 = train_one_case("Case2", model2, optimizer2, criterion, device, EPOCHS)

"""# Trường hợp 3: Freeze CNN, train Text + Fusion
model3 = FusionModel() độc lập.
"""

model3 = FusionModel()

for p in model3.image.parameters():
    p.requires_grad = False  # CNN freeze

for p in model3.text.parameters():
    p.requires_grad = True   # text train

optimizer3 = torch.optim.Adam([
    {"params": model3.text.parameters(), "lr": 1e-4},
    {"params": model3.fc.parameters(),   "lr": 1e-3},
])

history3 = train_one_case("Case3", model3, optimizer3, criterion, device, EPOCHS)

"""# Trường hợp 4: Train Full - CNN + Text + Fusion
model4 = FusionModel() độc lập.
"""

model4 = FusionModel()

for p in model4.parameters():
    p.requires_grad = True  # train toan bo

optimizer4 = torch.optim.Adam([
    {"params": model4.image.parameters(), "lr": 1e-4},
    {"params": model4.text.parameters(),  "lr": 1e-4},
    {"params": model4.fc.parameters(),    "lr": 1e-3},
])

history4 = train_one_case("Case4", model4, optimizer4, criterion, device, EPOCHS)

"""# So sánh 4 case trên test set"""

results = {
    "Case1 (freeze CNN+Text)": history1,
    "Case2 (freeze Text)":     history2,
    "Case3 (freeze CNN)":      history3,
    "Case4 (train full)":      history4,
}

print(f"{'Case':30}{'Final Test Loss':>18}{'Final Test Acc':>18}")
for name, h in results.items():
    print(f"{name:30}{h['test_loss'][-1]:>18.4f}{h['test_acc'][-1]:>18.4f}")

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
for name, h in results.items():
    plt.plot(h["test_loss"], marker='o', label=name)
plt.title("Test Loss theo epoch")
plt.xlabel("Epoch"); plt.ylabel("Loss"); plt.legend()

plt.subplot(1,2,2)
for name, h in results.items():
    plt.plot(h["test_acc"], marker='o', label=name)
plt.title("Test Accuracy theo epoch")
plt.xlabel("Epoch"); plt.ylabel("Accuracy"); plt.legend()

plt.tight_layout()
plt.show()

for model_name, m in [("model1", model1), ("model2", model2), ("model3", model3), ("model4", model4)]:
    print(f"===== {model_name} =====")
    for name, param in m.named_parameters():
        print(f"{name:35}{param.requires_grad}")
    print()