// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Checkpoints() {
  return window['go']['main']['App']['Checkpoints']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function LoadCheckpoint(arg1) {
  return window['go']['main']['App']['LoadCheckpoint'](arg1);
}

export function Predict(arg1, arg2) {
  return window['go']['main']['App']['Predict'](arg1, arg2);
}
