// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Checkpoints():Promise<main.CheckpointsResp>;

export function Health():Promise<main.HealthResp>;

export function LoadCheckpoint(arg1:string):Promise<main.HealthResp>;

export function Predict(arg1:string,arg2:string):Promise<main.PredictResp>;
